### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Mr1meng** [taishan1994/BERT-Relation-Extraction#6]
Traceback (most recent call last):
  File "D:\BERT-Relation-Extraction-main\re_main.py", line 189, in <module>
    main(data_name)
  File "D:\BERT-Relation-Extraction-main\re_main.py", line 181, in main
    train.train()
  File "D:\BERT-Relation-Extraction-main\re_main.py", line 53, in train
    output = self.model(input_ids, attention_mask, token_type_ids, labels)
  File "C:\Users\mqx\.conda\envs\bert2\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\BERT-Relation-Extraction-main\model.py", line 55, in forward
    bert_output = self.bert(input_ids=input_ids)
  File "C:\Users\mqx\.conda\envs\bert2\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mqx\.conda\envs\bert2\lib\site-packages\transformers\models\bert\modeling_bert.py", line 974, in forward
    batch_size, seq_length = input_shape
ValueError: not enough values to unpack (expected 2, got 1)
大佬，请问在训练关系抽取模型时会报这个错是什么原因呢

**Comment by taishan1994** [comment]
batch_size, seq_length = input_shape
input_shape期望有两个维度，但是只有一个维度。

**Comment by Banshan6** [comment]
同求，请问大佬们这个咋改？

**Comment by yinjihu** [comment]
同求，有大佬们知道咋改吗？快救救孩子吧
